### PR TITLE
Merge to main

### PR DESCRIPTION
**Pull request by mattmazzone**

### CODE REVIEW

**Comment by mattmazzone** [comment]
You can use github desktop or gitkraken to resolve the merge conflict and approve the PR. Cart page needs to be reviewed, maybe we'll give it its own page instead of having it in the nav bar

**Comment by mattmazzone** [comment]
@AdampBoucher

**Comment by AdampBoucher** [comment]
I fixed the merge conflicts, but I can't merge since it's blocked (i don't have access). You may have to do the merging @mattmazzone

**Review by AdampBoucher — APPROVED** [review]
Oh I think I figured it out @mattmazzone

**Pull request merged**
